title: "Tanasak Wanglomklang"
description: "PhD Candidate in Mechanical Engineering | Control System |Robust Optimization | Acoustic Simulation | Machine Learning"
baseurl: "" # Leave this blank for GitHub Pages
url: "https://twanglom.github.io"

theme: minimal-mistakes-jekyll # Use the theme you’ve installed

author:
  name: "Tanasak Wanglomklang"
  email: "your-email@example.com"
  github: "https://github.com/twanglom"
  linkedin: "https://linkedin.com/in/Thanasak Wanglomklang"

