title: "Thanasak Wanglomklang"
description: "PhD Candidate | Robust Optimization | Acoustic Simulation | Control Systems"
baseurl: "" # Leave this blank for GitHub Pages
url: "https://twanglom.github.io"

theme: minimal-mistakes-jekyll # Use Minimal Mistakes theme

author:
  name: "Tanasak Wanglomklang"
  email: "your-email@example.com"
  github: "https://github.com/twanglom"
  linkedin: "https://linkedin.com/in/Thanasak Wanglomklang"

header_pages:
  - index.md
  - about.md
  - projects.md
  - skills.md
  - contact.md

